/**
 * Hash-type reference database: detection + cracking metadata.
 *
 * hashcat modes are taken from hashcat's example_hashes table (the mode numbers
 * are factual); John formats are the canonical `--format=` names. Descriptions
 * are written here in our own words. "category"/"context" explain what the hash
 * is and where it typically comes from (especially credential hashes a
 * pentester runs into). Where hashcat has no mode for a type, hashcatMode is
 * omitted; where the John format is unknown it is omitted rather than guessed.
 */

export type Confidence = "high" | "medium" | "low";

export interface HashType {
  id: string;
  name: string;
  /** Where it comes from / what it belongs to. */
  category: string;
  /** One-line explanation of the hash and how it's usually obtained. */
  context: string;
  confidence: Confidence;
  /** hashcat `-m` mode, if crackable with hashcat. */
  hashcatMode?: number;
  /** John the Ripper `--format=` name, if supported. */
  johnFormat?: string;
  /** Extra caveat (tooling notes, weaknesses, etc.). */
  note?: string;
}

export interface StructuredDetector extends HashType {
  match: (s: string) => boolean;
  /**
   * If the input matched this type's marker but is structurally invalid (e.g.
   * right prefix, wrong length), return a human warning; otherwise undefined.
   */
  malformedReason?: (s: string) => string | undefined;
}

/**
 * Structured / prefixed formats — checked in order, most specific first. These
 * are high-signal: the prefix or layout usually pins the type exactly.
 */
export const STRUCTURED_DETECTORS: StructuredDetector[] = [
  // ---- Active Directory / Kerberos ----
  {
    id: "krb5tgs-23",
    name: "Kerberos 5 TGS-REP (etype 23, RC4-HMAC)",
    category: "Active Directory · Kerberos",
    context:
      "Kerberoasting: a service ticket (TGS-REP) requested for an SPN, encrypted with the service account's NTLM hash. Crack offline to recover the account's cleartext password.",
    confidence: "high",
    hashcatMode: 13100,
    johnFormat: "krb5tgs",
    match: (s) => /^\$krb5tgs\$23\$/.test(s),
  },
  {
    id: "krb5tgs-17",
    name: "Kerberos 5 TGS-REP (etype 17, AES-128)",
    category: "Active Directory · Kerberos",
    context: "Kerberoasting with AES-128 tickets. Slower to crack than RC4.",
    confidence: "high",
    hashcatMode: 19600,
    johnFormat: "krb5tgs",
    match: (s) => /^\$krb5tgs\$17\$/.test(s),
  },
  {
    id: "krb5tgs-18",
    name: "Kerberos 5 TGS-REP (etype 18, AES-256)",
    category: "Active Directory · Kerberos",
    context: "Kerberoasting with AES-256 tickets. Slowest of the TGS variants.",
    confidence: "high",
    hashcatMode: 19700,
    johnFormat: "krb5tgs",
    match: (s) => /^\$krb5tgs\$18\$/.test(s),
  },
  {
    id: "krb5tgs",
    name: "Kerberos 5 TGS-REP (etype unspecified)",
    category: "Active Directory · Kerberos",
    context:
      "A Kerberos service ticket from Kerberoasting whose encryption type isn't one of the common 23/17/18 variants. Check the etype field to pick the right hashcat mode.",
    confidence: "medium",
    johnFormat: "krb5tgs",
    note: "Mode depends on etype: 23→13100, 17→19600, 18→19700.",
    // Only fire for etypes the specific detectors above don't already cover, so
    // a normal $krb5tgs$23$ hash isn't reported twice.
    match: (s) => /^\$krb5tgs\$/.test(s) && !/^\$krb5tgs\$(23|17|18)\$/.test(s),
  },
  {
    id: "krb5asrep-23",
    name: "Kerberos 5 AS-REP (etype 23, RC4-HMAC)",
    category: "Active Directory · Kerberos",
    context:
      "AS-REP Roasting: obtained for accounts with 'Do not require Kerberos pre-authentication' set. Crack offline to recover the user's password.",
    confidence: "high",
    hashcatMode: 18200,
    johnFormat: "krb5asrep",
    match: (s) => /^\$krb5asrep\$(23\$)?/.test(s),
  },
  {
    id: "krb5pa",
    name: "Kerberos 5 AS-REQ Pre-Auth (etype 23)",
    category: "Active Directory · Kerberos",
    context:
      "Captured Kerberos pre-authentication (encrypted timestamp). Crack offline to recover the user's password.",
    confidence: "high",
    hashcatMode: 7500,
    johnFormat: "krb5pa-sha1",
    match: (s) => /^\$krb5pa\$23\$/.test(s) || /^\$krb5pre\$/.test(s),
  },
  {
    id: "krb5pa-17",
    name: "Kerberos 5 AS-REQ Pre-Auth (etype 17, AES-128)",
    category: "Active Directory · Kerberos",
    context: "Captured Kerberos pre-authentication encrypted with AES-128.",
    confidence: "high",
    hashcatMode: 19800,
    johnFormat: "krb5pa-sha1",
    match: (s) => /^\$krb5pa\$17\$/.test(s),
  },
  {
    id: "krb5pa-18",
    name: "Kerberos 5 AS-REQ Pre-Auth (etype 18, AES-256)",
    category: "Active Directory · Kerberos",
    context: "Captured Kerberos pre-authentication encrypted with AES-256.",
    confidence: "high",
    hashcatMode: 19900,
    johnFormat: "krb5pa-sha1",
    match: (s) => /^\$krb5pa\$18\$/.test(s),
  },
  // ---- NetNTLM (challenge/response) ----
  {
    id: "netntlmv2",
    name: "NetNTLMv2",
    category: "Windows · NetNTLM",
    context:
      "Net-NTLMv2 challenge/response captured over the wire (Responder, MITM, coerced SMB auth). Crack offline, or relay it with ntlmrelayx instead of cracking.",
    confidence: "high",
    hashcatMode: 5600,
    johnFormat: "netntlmv2",
    match: (s) =>
      /^[^:\s]*::[^:]*:[0-9a-fA-F]{16}:[0-9a-fA-F]{32}:[0-9a-fA-F]+$/.test(s),
  },
  {
    id: "netntlmv1",
    name: "NetNTLMv1",
    category: "Windows · NetNTLM",
    context:
      "Net-NTLMv1 challenge/response — weak. Crack offline, or with a fixed challenge (1122334455667788) submit to crack.sh for guaranteed NT-hash recovery.",
    confidence: "high",
    hashcatMode: 5500,
    johnFormat: "netntlm",
    match: (s) =>
      /^[^:\s]*::[^:]*:[0-9a-fA-F]{48}:[0-9a-fA-F]{48}:[0-9a-fA-F]{16}$/.test(s),
  },
  // ---- pwdump / SAM line ----
  {
    id: "pwdump",
    name: "pwdump line (LM:NTLM)",
    category: "Windows · SAM/NTDS",
    context:
      "user:rid:LM:NT::: dump from the SAM/NTDS (secretsdump, pwdump). Feed the NT hash to mode 1000; the NT hash also works directly for pass-the-hash.",
    confidence: "high",
    hashcatMode: 1000,
    johnFormat: "nt",
    note: "The LM half (if not blank aad3b435…) is hashcat -m 3000 / John format=lm.",
    match: (s) => /^[^:\s]*:\d+:[0-9a-fA-F]{32}:[0-9a-fA-F]{32}:::?$/.test(s),
  },
  // ---- Unix shadow ----
  {
    id: "sha512crypt",
    name: "sha512crypt ($6$)",
    category: "Linux · /etc/shadow",
    context: "Modern Linux shadow password (SHA-512, 5000+ rounds).",
    confidence: "high",
    hashcatMode: 1800,
    johnFormat: "sha512crypt",
    match: (s) => /^\$6\$/.test(s),
  },
  {
    id: "sha256crypt",
    name: "sha256crypt ($5$)",
    category: "Linux · /etc/shadow",
    context: "Linux shadow password (SHA-256, 5000+ rounds).",
    confidence: "high",
    hashcatMode: 7400,
    johnFormat: "sha256crypt",
    match: (s) => /^\$5\$/.test(s),
  },
  {
    id: "md5crypt",
    name: "md5crypt ($1$)",
    category: "Linux · /etc/shadow",
    context: "Older Unix shadow password — also Cisco IOS 'enable secret 5'.",
    confidence: "high",
    hashcatMode: 500,
    johnFormat: "md5crypt",
    match: (s) => /^\$1\$/.test(s),
  },
  {
    id: "yescrypt",
    name: "yescrypt ($y$)",
    category: "Linux · /etc/shadow",
    context:
      "Default shadow hash on recent Debian/Ubuntu/Fedora. Not supported by hashcat — crack with John.",
    confidence: "high",
    johnFormat: "yescrypt",
    note: "hashcat has no yescrypt mode; use John the Ripper.",
    match: (s) => /^\$y\$/.test(s),
  },
  {
    id: "scrypt-shadow",
    name: "scrypt shadow ($7$)",
    category: "Linux · /etc/shadow",
    context:
      "A $7$-prefixed scrypt shadow password (some BSD/Linux builds). Crack with John; hashcat's generic scrypt mode is 8900.",
    confidence: "medium",
    note: "$7$ is scrypt; hashcat's generic scrypt is -m 8900 but layout differs.",
    match: (s) => /^\$7\$/.test(s),
  },
  {
    id: "sha1crypt",
    name: "sha1crypt ($sha1$)",
    category: "Unix · /etc/shadow",
    context: "NetBSD sha1crypt shadow password.",
    confidence: "high",
    hashcatMode: 15100,
    johnFormat: "sha1crypt",
    match: (s) => /^\$sha1\$/.test(s),
  },
  {
    id: "argon2",
    name: "Argon2 ($argon2*$)",
    category: "Linux · /etc/shadow",
    context:
      "Argon2 (i/d/id) — modern memory-hard KDF, increasingly used for shadow and app password stores. Crack with John.",
    confidence: "high",
    johnFormat: "argon2",
    note: "hashcat Argon2 support is very recent/limited; John handles all variants.",
    match: (s) => /^\$argon2(id|i|d)\$/.test(s),
  },
  // ---- bcrypt / app frameworks / CMS ----
  {
    id: "bcrypt",
    name: "bcrypt ($2*$)",
    category: "Web app · password store",
    context:
      "bcrypt (Blowfish) — very common in app databases (Laravel, Spring, Node bcrypt, Rails). Deliberately slow.",
    confidence: "high",
    hashcatMode: 3200,
    johnFormat: "bcrypt",
    match: (s) => /^\$2[abxy]?\$\d{2}\$[./A-Za-z0-9]{20,}$/.test(s),
  },
  {
    id: "phpass",
    name: "phpass ($P$ / $H$)",
    category: "Web app · CMS",
    context: "WordPress, phpBB3 and legacy Drupal 7 password hashes (phpass).",
    confidence: "high",
    hashcatMode: 400,
    johnFormat: "phpass",
    match: (s) => /^\$[PH]\$[./A-Za-z0-9]{31}$/.test(s),
  },
  {
    id: "drupal7",
    name: "Drupal 7 ($S$)",
    category: "Web app · CMS",
    context: "Drupal 7 password hash (SHA-512 based, iterated).",
    confidence: "high",
    hashcatMode: 7900,
    johnFormat: "Drupal7",
    match: (s) => /^\$S\$[./A-Za-z0-9]{52}$/.test(s),
  },
  {
    id: "mediawiki-b",
    name: "MediaWiki ($B$)",
    category: "Web app · CMS",
    context: "MediaWiki 'B'-type password hash (salted MD5: md5(salt.md5(pw))).",
    confidence: "high",
    hashcatMode: 3711,
    johnFormat: "mediawiki",
    match: (s) => /^\$B\$[^$]*\$[0-9a-fA-F]{32}$/.test(s),
  },
  {
    id: "django-pbkdf2",
    name: "Django (PBKDF2-SHA256)",
    category: "Web app · framework",
    context: "Django default password hash (PBKDF2-HMAC-SHA256).",
    confidence: "high",
    hashcatMode: 10000,
    johnFormat: "django",
    match: (s) => /^pbkdf2_sha256\$/.test(s),
  },
  {
    id: "django-sha1",
    name: "Django (SHA-1, legacy)",
    category: "Web app · framework",
    context: "Older Django salted-SHA1 password format (sha1$salt$digest).",
    confidence: "medium",
    johnFormat: "django",
    match: (s) => /^sha1\$[^$]+\$[0-9a-fA-F]{40}$/.test(s),
  },
  {
    id: "apr1",
    name: "Apache apr1-MD5 ($apr1$)",
    category: "Web server · htpasswd",
    context: "Apache htpasswd MD5 (APR1).",
    confidence: "high",
    hashcatMode: 1600,
    johnFormat: "md5crypt",
    match: (s) => /^\$apr1\$/.test(s),
  },
  // ---- Cisco / network gear ----
  {
    id: "cisco4",
    name: "Cisco IOS type 4 (SHA-256)",
    category: "Network · Cisco",
    context:
      "Cisco IOS 'type 4' secret — a single unsalted SHA-256 (a flawed design Cisco later deprecated). 43-char base64.",
    confidence: "medium",
    hashcatMode: 5700,
    johnFormat: "cisco4",
    match: (s) => /^[./A-Za-z0-9]{43}$/.test(s),
  },
  {
    id: "cisco8",
    name: "Cisco IOS type 8 ($8$)",
    category: "Network · Cisco",
    context: "Cisco IOS 'type 8' password (PBKDF2-HMAC-SHA256).",
    confidence: "high",
    hashcatMode: 9200,
    johnFormat: "pbkdf2-hmac-sha256",
    match: (s) => /^\$8\$/.test(s),
  },
  {
    id: "cisco9",
    name: "Cisco IOS type 9 ($9$)",
    category: "Network · Cisco",
    context: "Cisco IOS 'type 9' password (scrypt).",
    confidence: "high",
    hashcatMode: 9300,
    johnFormat: "scrypt",
    match: (s) => /^\$9\$/.test(s),
  },
  {
    id: "cisco-type7",
    name: "Cisco type 7 (reversible)",
    category: "Network · Cisco",
    context:
      "Cisco 'type 7' is obfuscation, not a hash — trivially reversible with no cracking needed (e.g. ciscot7, online decoders).",
    confidence: "low",
    note: "Not a real hash; decode it directly instead of cracking. No hashcat mode.",
    match: (s) => /^07[0-9A-Fa-f]{4,}$/.test(s) && s.length % 2 === 0,
  },
  {
    id: "juniper-9",
    name: "Juniper ScreenOS / Netscreen ($9$)",
    category: "Network · Juniper",
    context:
      "Juniper $9$ encrypted secret. ScreenOS hashes crack with hashcat 22; the IVE/SSLVPN sha1crypt variant is mode 501.",
    confidence: "medium",
    hashcatMode: 22,
    note: "Juniper IVE (SSL-VPN) PBKDF/sha1crypt form is hashcat -m 501 instead.",
    match: (s) => /^\$9\$[./A-Za-z0-9]{20,}$/.test(s),
  },
  {
    id: "fortigate",
    name: "FortiGate (FortiOS)",
    category: "Network · Fortinet",
    context:
      "FortiGate FortiOS password hash (SHA-1 with a salt and 'AK1' prefix in config).",
    confidence: "medium",
    hashcatMode: 7000,
    johnFormat: "fortigate",
    match: (s) => /^AK1[A-Za-z0-9+/=]{40,}$/.test(s),
  },
  // ---- Directory / LDAP ----
  {
    id: "ldap-ssha",
    name: "LDAP {SSHA} (salted SHA-1)",
    category: "Directory · OpenLDAP",
    context: "OpenLDAP salted SHA-1 userPassword.",
    confidence: "high",
    hashcatMode: 111,
    johnFormat: "ssha",
    match: (s) => /^\{SSHA\}/.test(s),
  },
  {
    id: "ldap-sha",
    name: "LDAP {SHA} (base64 SHA-1)",
    category: "Directory · OpenLDAP",
    context: "OpenLDAP plain SHA-1 userPassword (base64, unsalted).",
    confidence: "high",
    hashcatMode: 101,
    johnFormat: "nsldap",
    match: (s) => /^\{SHA\}/.test(s),
  },
  {
    id: "ldap-ssha256",
    name: "LDAP {SSHA256}",
    category: "Directory · OpenLDAP",
    context: "OpenLDAP salted SHA-256 userPassword (base64).",
    confidence: "high",
    hashcatMode: 1411,
    johnFormat: "ssha256",
    match: (s) => /^\{SSHA256\}/.test(s),
  },
  {
    id: "ldap-ssha512",
    name: "LDAP {SSHA512}",
    category: "Directory · OpenLDAP",
    context: "OpenLDAP salted SHA-512 userPassword (base64).",
    confidence: "high",
    hashcatMode: 1711,
    johnFormat: "ssha512",
    match: (s) => /^\{SSHA512\}/.test(s),
  },
  {
    id: "ldap-md5",
    name: "LDAP {MD5} / {SMD5}",
    category: "Directory · OpenLDAP",
    context: "OpenLDAP base64 MD5 or salted-MD5 userPassword.",
    confidence: "medium",
    note: "{MD5} maps to hashcat -m 0 after base64-decode; {SMD5} is salted MD5.",
    match: (s) => /^\{S?MD5\}/.test(s),
  },
  // ---- Databases ----
  {
    id: "mysql41",
    name: "MySQL 4.1+ (SHA1(SHA1(pw)))",
    category: "Database · MySQL",
    context: "MySQL 4.1+ password hash (the leading '*' form from mysql.user).",
    confidence: "high",
    hashcatMode: 300,
    johnFormat: "mysql-sha1",
    match: (s) => /^\*[0-9a-fA-F]{40}$/.test(s),
  },
  {
    id: "postgres-md5",
    name: "PostgreSQL md5 (md5 + username salt)",
    category: "Database · PostgreSQL",
    context:
      "PostgreSQL 'md5'-prefixed password = md5(password + username). Username is the salt.",
    confidence: "high",
    hashcatMode: 12,
    johnFormat: "postgres",
    match: (s) => /^md5[0-9a-fA-F]{32}$/.test(s),
  },
  {
    id: "mssql2012",
    name: "MSSQL 2012 / 2014 (SHA-512)",
    category: "Database · MSSQL",
    context:
      "SQL Server 2012/2014 password hash: optional 0x0200 header, 4-byte (8-hex) salt, then a SHA-512 (128-hex) digest.",
    confidence: "high",
    hashcatMode: 1731,
    johnFormat: "mssql12",
    // The 0x0200 header is MSSQL 2012/2014's version marker, so trust it even if
    // the body length is off — but flag it as malformed in that case.
    match: (s) =>
      /^0x0200[0-9a-fA-F]+$/i.test(s) || /^[0-9a-fA-F]{136}$/.test(s),
    malformedReason: (s) => {
      if (!/^0x0200/i.test(s)) return undefined; // bare form is length-exact
      const body = s.slice(6);
      if (body.length === 136) return undefined;
      return `The 0x0200 marker indicates MSSQL 2012/2014, but the body is ${body.length} hex chars — a valid hash needs 136 (8-hex salt + 128-hex SHA-512). It can't be cracked as-is.`;
    },
  },
  {
    id: "mssql2005",
    name: "MSSQL 2005 (SHA-1)",
    category: "Database · MSSQL",
    context:
      "SQL Server 2005 password hash: optional 0x0100 header, 4-byte (8-hex) salt, then a SHA-1 (40-hex) digest.",
    confidence: "high",
    hashcatMode: 132,
    johnFormat: "mssql05",
    match: (s) => /^(0x0100)?[0-9a-fA-F]{8}[0-9a-fA-F]{40}$/i.test(s),
  },
  {
    id: "mssql2000",
    name: "MSSQL 2000 (SHA-1, case-sensitive + upper)",
    category: "Database · MSSQL",
    context:
      "SQL Server 2000 password hash: optional 0x0100 header, 4-byte (8-hex) salt, then two SHA-1 digests (80-hex) — one of the password, one of its upper-cased form.",
    confidence: "high",
    hashcatMode: 131,
    johnFormat: "mssql",
    match: (s) => /^(0x0100)?[0-9a-fA-F]{8}[0-9a-fA-F]{80}$/i.test(s),
  },
  {
    id: "oracle11g",
    name: "Oracle 11g (SHA-1, 'S:')",
    category: "Database · Oracle",
    context:
      "Oracle 11g password hash: 40-hex SHA-1 followed by a 20-hex salt (sometimes shown with an 'S:' prefix).",
    confidence: "high",
    hashcatMode: 112,
    johnFormat: "oracle11",
    match: (s) => /^(S:)?[0-9a-fA-F]{40}[0-9a-fA-F]{20}$/i.test(s),
  },
  {
    id: "oracle12c",
    name: "Oracle 12c (PBKDF2-SHA512, 'T:')",
    category: "Database · Oracle",
    context: "Oracle 12c password hash (PBKDF2-HMAC-SHA512), often shown as 'T:…'.",
    confidence: "high",
    hashcatMode: 12300,
    johnFormat: "oracle12c",
    match: (s) => /^(T:)?[0-9a-fA-F]{160}$/i.test(s),
  },
  {
    id: "sybase-ase",
    name: "Sybase ASE",
    category: "Database · Sybase",
    context: "Sybase ASE password hash (0xc007… salted SHA-256 form).",
    confidence: "medium",
    hashcatMode: 8000,
    johnFormat: "sybasease",
    match: (s) => /^0xc007[0-9a-fA-F]{1028}$/i.test(s),
  },
  // ---- Tokens / Wi-Fi / network auth ----
  {
    id: "jwt",
    name: "JWT (JSON Web Token)",
    category: "Web app · auth token",
    context:
      "A JSON Web Token. If HMAC-signed (HS256/384/512), hashcat 16500 can brute-force the signing secret to forge tokens.",
    confidence: "high",
    hashcatMode: 16500,
    note: "RS/ES (asymmetric) tokens aren't crackable this way — only HMAC (HS*) secrets.",
    match: (s) =>
      /^eyJ[A-Za-z0-9_-]+\.eyJ[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+$/.test(s),
  },
  {
    id: "wpa",
    name: "WPA/WPA2 (PMKID/EAPOL)",
    category: "Wi-Fi · WPA",
    context: "Wi-Fi WPA/WPA2 handshake or PMKID in hashcat 22000 format.",
    confidence: "high",
    hashcatMode: 22000,
    johnFormat: "wpapsk",
    match: (s) => /^WPA\*0[12]\*/.test(s),
  },
  {
    id: "ipmi2-rakp",
    name: "IPMI2 RAKP HMAC-SHA1",
    category: "Network · IPMI/BMC",
    context:
      "IPMI 2.0 RAKP authentication hash pulled from a BMC (HMAC-SHA1). Servers often expose this and it cracks fast.",
    confidence: "medium",
    hashcatMode: 7300,
    johnFormat: "rakp",
    match: (s) => /^[0-9a-fA-F]{130,}:[0-9a-fA-F]{40}$/.test(s),
  },
  {
    id: "sip",
    name: "SIP digest (MD5 challenge/response)",
    category: "Network · VoIP/SIP",
    context: "SIP authentication digest captured from VoIP traffic (MD5-based).",
    confidence: "medium",
    hashcatMode: 11400,
    johnFormat: "sip",
    match: (s) => /^\$sip\$/.test(s),
  },
  {
    id: "snmpv3",
    name: "SNMPv3 HMAC",
    category: "Network · SNMP",
    context: "SNMPv3 USM authentication hash (HMAC-MD5/SHA) captured from traffic.",
    confidence: "medium",
    hashcatMode: 25100,
    match: (s) => /^\$SNMPv3\$/.test(s),
  },
  // ---- PBKDF2 generic forms ----
  {
    id: "pbkdf2-sha256",
    name: "PBKDF2-HMAC-SHA256 (generic)",
    category: "Generic · PBKDF2",
    context:
      "A generic PBKDF2-HMAC-SHA256 hash (sha256:rounds:salt:hash). Used by many frameworks.",
    confidence: "high",
    hashcatMode: 10900,
    johnFormat: "pbkdf2-hmac-sha256",
    match: (s) => /^sha256:\d+:[A-Za-z0-9+/=]+:[A-Za-z0-9+/=]+$/.test(s),
  },
  {
    id: "pbkdf2-sha512",
    name: "PBKDF2-HMAC-SHA512 (generic)",
    category: "Generic · PBKDF2",
    context: "A generic PBKDF2-HMAC-SHA512 hash (sha512:rounds:salt:hash).",
    confidence: "high",
    hashcatMode: 12100,
    johnFormat: "pbkdf2-hmac-sha512",
    match: (s) => /^sha512:\d+:[A-Za-z0-9+/=]+:[A-Za-z0-9+/=]+$/.test(s),
  },
  {
    id: "pbkdf2-sha1",
    name: "PBKDF2-HMAC-SHA1 (generic)",
    category: "Generic · PBKDF2",
    context: "A generic PBKDF2-HMAC-SHA1 hash (sha1:rounds:salt:hash).",
    confidence: "high",
    hashcatMode: 12000,
    johnFormat: "pbkdf2-hmac-sha1",
    match: (s) => /^sha1:\d+:[A-Za-z0-9+/=]+:[A-Za-z0-9+/=]+$/.test(s),
  },
  {
    id: "pbkdf2-md5",
    name: "PBKDF2-HMAC-MD5 (generic)",
    category: "Generic · PBKDF2",
    context: "A generic PBKDF2-HMAC-MD5 hash (md5:rounds:salt:hash).",
    confidence: "high",
    hashcatMode: 11900,
    johnFormat: "pbkdf2-hmac-md5",
    match: (s) => /^md5:\d+:[A-Za-z0-9+/=]+:[A-Za-z0-9+/=]+$/.test(s),
  },
  // ---- macOS ----
  {
    id: "macos-pbkdf2",
    name: "macOS 10.8+ (PBKDF2-SHA512)",
    category: "macOS · login",
    context: "macOS 10.8+ user password (PBKDF2-HMAC-SHA512) from a plist .ShadowHashData.",
    confidence: "high",
    hashcatMode: 7100,
    johnFormat: "PBKDF2-HMAC-SHA512",
    match: (s) => /^\$ml\$/.test(s),
  },
  {
    id: "macos-107",
    name: "macOS 10.7 (salted SHA-512)",
    category: "macOS · login",
    context: "macOS 10.7 Lion password hash (salted SHA-512, 136-hex).",
    confidence: "medium",
    hashcatMode: 1722,
    johnFormat: "xsha512",
    match: (s) => /^[0-9a-fA-F]{136}$/.test(s),
  },
  // ---- Disk / containers / archives / wallets / docs ----
  {
    id: "luks",
    name: "LUKS (disk encryption)",
    category: "Disk encryption",
    context: "LUKS encrypted volume header (Linux full-disk encryption).",
    confidence: "high",
    hashcatMode: 14600,
    johnFormat: "luks",
    match: (s) => /^\$luks\$/.test(s),
  },
  {
    id: "veracrypt",
    name: "VeraCrypt volume",
    category: "Disk encryption",
    context:
      "VeraCrypt encrypted volume. hashcat modes 137xx select the PRF/cipher; extract with veracrypt2hashcat.",
    confidence: "high",
    note: "Mode is in the 13700–13799 range depending on PRF/cipher combination.",
    match: (s) => /^\$veracrypt\$/i.test(s),
  },
  {
    id: "keepass",
    name: "KeePass database",
    category: "Password manager",
    context: "KeePass 1.x/2.x database master key (extract with keepass2john).",
    confidence: "high",
    hashcatMode: 13400,
    johnFormat: "KeePass",
    match: (s) => /^\$keepass\$/.test(s),
  },
  {
    id: "lastpass",
    name: "LastPass vault",
    category: "Password manager",
    context: "LastPass vault key (PBKDF2-HMAC-SHA256 over the master password).",
    confidence: "high",
    hashcatMode: 6800,
    johnFormat: "lp",
    match: (s) => /^\$lastpass\$/.test(s),
  },
  {
    id: "1password",
    name: "1Password (AgileKeychain)",
    category: "Password manager",
    context: "1Password vault key derivation (PBKDF2). cloudkeychain vaults are hashcat -m 8200.",
    confidence: "medium",
    hashcatMode: 6600,
    note: "1Password cloudkeychain is mode 8200; iPhone passcode is 26500.",
    match: (s) => /^\$ASN\$|^\$1[Pp]assword\$|^\$opdata\$/.test(s),
  },
  {
    id: "bitcoin-wallet",
    name: "Bitcoin / Litecoin wallet.dat",
    category: "Crypto wallet",
    context: "Encrypted Bitcoin/Litecoin wallet key (extract with bitcoin2john).",
    confidence: "high",
    hashcatMode: 11300,
    johnFormat: "bitcoin",
    match: (s) => /^\$bitcoin\$/.test(s),
  },
  {
    id: "ethereum-presale",
    name: "Ethereum wallet (presale / PBKDF2 / SCRYPT)",
    category: "Crypto wallet",
    context:
      "Ethereum wallet key. hashcat: presale 16300, PBKDF2 keystore 15700→use 15600, SCRYPT keystore 15700. Extract with ethereum2john.",
    confidence: "high",
    note: "Modes: PBKDF2 keystore 15600, SCRYPT keystore 15700, presale 16300.",
    match: (s) => /^\$ethereum\$/.test(s),
  },
  {
    id: "grub2",
    name: "GRUB 2 password (PBKDF2-SHA512)",
    category: "Bootloader",
    context: "GRUB 2 boot password (grub.pbkdf2.sha512.… PBKDF2-HMAC-SHA512).",
    confidence: "high",
    hashcatMode: 7200,
    johnFormat: "grub",
    match: (s) => /^grub\.pbkdf2\.sha512\./.test(s),
  },
  {
    id: "office2013",
    name: "MS Office 2013+ ",
    category: "Document",
    context: "Microsoft Office 2013/2016/2019 document encryption (SHA-512, AES).",
    confidence: "high",
    hashcatMode: 9600,
    johnFormat: "office",
    match: (s) => /^\$office\$\*2013\*/.test(s),
  },
  {
    id: "office2010",
    name: "MS Office 2010",
    category: "Document",
    context: "Microsoft Office 2010 document encryption (SHA-1, AES).",
    confidence: "high",
    hashcatMode: 9500,
    johnFormat: "office",
    match: (s) => /^\$office\$\*2010\*/.test(s),
  },
  {
    id: "office2007",
    name: "MS Office 2007",
    category: "Document",
    context: "Microsoft Office 2007 document encryption (SHA-1, AES).",
    confidence: "high",
    hashcatMode: 9400,
    johnFormat: "office",
    match: (s) => /^\$office\$\*2007\*/.test(s),
  },
  {
    id: "pdf17",
    name: "PDF 1.7 (Acrobat 9, AES-256)",
    category: "Document",
    context: "PDF 1.7 Level 8 (Acrobat 9+) encryption. Extract with pdf2john.",
    confidence: "high",
    hashcatMode: 10700,
    johnFormat: "pdf",
    match: (s) => /^\$pdf\$5\*/.test(s),
  },
  {
    id: "pdf-legacy",
    name: "PDF (older, RC4/AES-128)",
    category: "Document",
    context:
      "Older PDF encryption (1.1–1.6). hashcat modes 10400–10600 depending on revision.",
    confidence: "high",
    note: "Modes: 10400/10410/10420 (rev2-3), 10500 (rev4), 10600 (rev5/6 owner pw).",
    johnFormat: "pdf",
    match: (s) => /^\$pdf\$[1234]\*/.test(s),
  },
  {
    id: "zip",
    name: "ZIP (AES / WinZip)",
    category: "Archive",
    context: "WinZip AES-encrypted archive (extract with zip2john). hashcat 13600.",
    confidence: "high",
    hashcatMode: 13600,
    johnFormat: "ZIP",
    match: (s) => /^\$zip2\$/.test(s),
  },
  {
    id: "pkzip",
    name: "PKZIP (legacy ZipCrypto)",
    category: "Archive",
    context:
      "Legacy PKZIP/ZipCrypto archive. hashcat 17200/17210/17220/17225 by compression layout.",
    confidence: "high",
    note: "Modes 17200–17225 depending on compressed/uncompressed/multi-file layout.",
    johnFormat: "PKZIP",
    match: (s) => /^\$pkzip2?\$/.test(s),
  },
  {
    id: "rar3",
    name: "RAR3 archive",
    category: "Archive",
    context: "RAR3-hp encrypted archive (extract with rar2john). hashcat 12500.",
    confidence: "high",
    hashcatMode: 12500,
    johnFormat: "rar",
    match: (s) => /^\$RAR3\$/.test(s),
  },
  {
    id: "rar5",
    name: "RAR5 archive",
    category: "Archive",
    context: "RAR5 encrypted archive (PBKDF2-HMAC-SHA256). hashcat 13000.",
    confidence: "high",
    hashcatMode: 13000,
    johnFormat: "rar5",
    match: (s) => /^\$rar5\$/.test(s),
  },
  {
    id: "7zip",
    name: "7-Zip archive",
    category: "Archive",
    context: "7-Zip AES-256 encrypted archive (extract with 7z2john). hashcat 11600.",
    confidence: "high",
    hashcatMode: 11600,
    johnFormat: "7z",
    match: (s) => /^\$7z\$/.test(s),
  },
];

/**
 * Plain-hex candidates keyed by hex length (ambiguous — multiple types share a
 * length, so we list them by descending likelihood). Lengths shown in hex
 * digits: 8=32-bit, 16=64-bit, 32=128-bit, 40=160-bit, 56=224-bit, 64=256-bit,
 * 96=384-bit, 128=512-bit.
 */
export const HEX_BY_LENGTH: Record<number, HashType[]> = {
  8: [
    {
      id: "crc32",
      name: "CRC-32",
      category: "Checksum",
      context: "A CRC-32 checksum (not a cryptographic hash).",
      confidence: "medium",
      hashcatMode: 11500,
      johnFormat: "crc32",
    },
    {
      id: "crc32c",
      name: "CRC-32C (Castagnoli)",
      category: "Checksum",
      context: "A CRC-32C checksum (different polynomial from plain CRC-32).",
      confidence: "low",
    },
    {
      id: "adler32",
      name: "Adler-32",
      category: "Checksum",
      context: "An Adler-32 checksum (used by zlib).",
      confidence: "low",
    },
    {
      id: "fnv32",
      name: "FNV-1/1a (32-bit)",
      category: "Checksum",
      context: "A 32-bit FNV non-cryptographic hash.",
      confidence: "low",
    },
  ],
  16: [
    {
      id: "mysql323",
      name: "MySQL323 (pre-4.1)",
      category: "Database · MySQL",
      context: "Legacy MySQL <4.1 password hash.",
      confidence: "high",
      hashcatMode: 200,
      johnFormat: "mysql",
    },
    {
      id: "crc64",
      name: "CRC-64",
      category: "Checksum",
      context: "A 64-bit CRC checksum (not cryptographic).",
      confidence: "low",
    },
    {
      id: "des-oracle",
      name: "DES / Oracle 7-10g (DES)",
      category: "Database · Oracle",
      context:
        "A 16-hex DES output — e.g. the legacy Oracle 7-10g password hash (usually paired with a username).",
      confidence: "low",
      hashcatMode: 3100,
      johnFormat: "oracle",
    },
  ],
  32: [
    {
      id: "md5",
      name: "MD5",
      category: "Raw hash",
      context: "MD5 digest — ubiquitous in app DBs and integrity checks.",
      confidence: "high",
      hashcatMode: 0,
      johnFormat: "raw-md5",
    },
    {
      id: "ntlm",
      name: "NTLM",
      category: "Windows · SAM/NTDS",
      context:
        "An NT hash (MD4 of UTF-16 password) from the SAM/NTDS. Crackable, and usable directly for pass-the-hash.",
      confidence: "high",
      hashcatMode: 1000,
      johnFormat: "nt",
    },
    {
      id: "md4",
      name: "MD4",
      category: "Raw hash",
      context: "Raw MD4 digest.",
      confidence: "low",
      hashcatMode: 900,
      johnFormat: "raw-md4",
    },
    {
      id: "lm",
      name: "LM",
      category: "Windows · legacy",
      context: "A half of an LM hash (very weak; legacy Windows).",
      confidence: "low",
      hashcatMode: 3000,
      johnFormat: "lm",
    },
    {
      id: "mscash",
      name: "Domain Cached Credentials (DCC/mscash)",
      category: "Windows · cached creds",
      context:
        "MS-CACHE v1 — cached domain logon hash (often shown with the username).",
      confidence: "low",
      hashcatMode: 1100,
      johnFormat: "mscash",
    },
    {
      id: "md5-half-sha1",
      name: "MD5(Half) / truncated digest",
      category: "Raw hash",
      context: "Could be the first/second half of a larger digest, or a halved MD5.",
      confidence: "low",
      hashcatMode: 5100,
      note: "hashcat 5100 is 'Half MD5' (first 16 bytes).",
    },
    {
      id: "radmin2",
      name: "RAdmin v2.x",
      category: "Remote admin",
      context: "Radmin v2 remote-admin password hash (MD5-based, 32-hex).",
      confidence: "low",
      hashcatMode: 9900,
      johnFormat: "radmin",
    },
    {
      id: "double-md5",
      name: "double MD5 — md5(md5(pw))",
      category: "Raw hash",
      context: "Iterated MD5 (md5(md5($pass))), seen in some legacy web apps.",
      confidence: "low",
      hashcatMode: 2600,
    },
    {
      id: "ripemd128",
      name: "RIPEMD-128",
      category: "Raw hash",
      context: "RIPEMD-128 digest (128-bit).",
      confidence: "low",
    },
    {
      id: "haval128",
      name: "HAVAL-128",
      category: "Raw hash",
      context: "HAVAL digest at 128-bit output.",
      confidence: "low",
    },
  ],
  40: [
    {
      id: "sha1",
      name: "SHA-1",
      category: "Raw hash",
      context: "SHA-1 digest.",
      confidence: "high",
      hashcatMode: 100,
      johnFormat: "raw-sha1",
    },
    {
      id: "ripemd160",
      name: "RIPEMD-160",
      category: "Raw hash",
      context: "RIPEMD-160 digest.",
      confidence: "medium",
      hashcatMode: 6000,
      johnFormat: "ripemd-160",
    },
    {
      id: "mysql41-raw",
      name: "MySQL 4.1+ (without '*')",
      category: "Database · MySQL",
      context: "MySQL 4.1+ hash body shown without the leading '*'.",
      confidence: "medium",
      hashcatMode: 300,
      johnFormat: "mysql-sha1",
    },
    {
      id: "tiger160",
      name: "Tiger-160",
      category: "Raw hash",
      context: "Tiger digest truncated to 160 bits.",
      confidence: "low",
    },
    {
      id: "has160",
      name: "HAS-160",
      category: "Raw hash",
      context: "HAS-160 (Korean KCDSA) digest.",
      confidence: "low",
    },
    {
      id: "sha1-half-256",
      name: "SHA-256(Half) / truncated 160-bit",
      category: "Raw hash",
      context: "Could be a truncation of a larger digest to 160 bits.",
      confidence: "low",
    },
  ],
  56: [
    {
      id: "sha224",
      name: "SHA-224",
      category: "Raw hash",
      context: "SHA-224 digest.",
      confidence: "high",
      hashcatMode: 1300,
      johnFormat: "raw-sha224",
    },
    {
      id: "sha3-224",
      name: "SHA3-224",
      category: "Raw hash",
      context: "SHA3-224 digest.",
      confidence: "low",
      hashcatMode: 17300,
    },
    {
      id: "keccak224",
      name: "Keccak-224",
      category: "Raw hash",
      context: "Original Keccak-224 (pre-SHA3 padding).",
      confidence: "low",
    },
    {
      id: "haval224",
      name: "HAVAL-224",
      category: "Raw hash",
      context: "HAVAL digest at 224-bit output.",
      confidence: "low",
    },
  ],
  64: [
    {
      id: "sha256",
      name: "SHA-256",
      category: "Raw hash",
      context: "SHA-256 digest.",
      confidence: "high",
      hashcatMode: 1400,
      johnFormat: "raw-sha256",
    },
    {
      id: "sha3-256",
      name: "SHA3-256",
      category: "Raw hash",
      context: "SHA3-256 digest.",
      confidence: "low",
      hashcatMode: 17400,
    },
    {
      id: "keccak256",
      name: "Keccak-256",
      category: "Raw hash",
      context: "Original Keccak-256 (used by Ethereum).",
      confidence: "low",
      hashcatMode: 17800,
    },
    {
      id: "ripemd256",
      name: "RIPEMD-256",
      category: "Raw hash",
      context: "RIPEMD-256 digest.",
      confidence: "low",
    },
    {
      id: "gost",
      name: "GOST R 34.11-94",
      category: "Raw hash",
      context: "Legacy Russian GOST hash (256-bit).",
      confidence: "low",
      hashcatMode: 6900,
      johnFormat: "gost",
    },
    {
      id: "streebog256",
      name: "Streebog-256 (GOST R 34.11-2012)",
      category: "Raw hash",
      context: "Russian GOST Streebog 256-bit hash.",
      confidence: "low",
      hashcatMode: 11700,
      johnFormat: "Streebog-256",
    },
    {
      id: "sm3",
      name: "SM3",
      category: "Raw hash",
      context: "Chinese national SM3 hash (256-bit).",
      confidence: "low",
    },
    {
      id: "blake2s",
      name: "BLAKE2s-256",
      category: "Raw hash",
      context: "BLAKE2s 256-bit digest.",
      confidence: "low",
    },
    {
      id: "haval256",
      name: "HAVAL-256",
      category: "Raw hash",
      context: "HAVAL digest at 256-bit output.",
      confidence: "low",
    },
    {
      id: "sha512-256",
      name: "SHA-512/256",
      category: "Raw hash",
      context: "SHA-512 truncated to 256 bits (or half of a SHA-512 output).",
      confidence: "low",
    },
  ],
  96: [
    {
      id: "sha384",
      name: "SHA-384",
      category: "Raw hash",
      context: "SHA-384 digest.",
      confidence: "high",
      hashcatMode: 10800,
      johnFormat: "raw-sha384",
    },
    {
      id: "sha3-384",
      name: "SHA3-384",
      category: "Raw hash",
      context: "SHA3-384 digest.",
      confidence: "low",
      hashcatMode: 17500,
    },
    {
      id: "keccak384",
      name: "Keccak-384",
      category: "Raw hash",
      context: "Original Keccak-384 (pre-SHA3 padding).",
      confidence: "low",
    },
  ],
  128: [
    {
      id: "sha512",
      name: "SHA-512",
      category: "Raw hash",
      context: "SHA-512 digest.",
      confidence: "high",
      hashcatMode: 1700,
      johnFormat: "raw-sha512",
    },
    {
      id: "whirlpool",
      name: "Whirlpool",
      category: "Raw hash",
      context: "Whirlpool digest (512-bit).",
      confidence: "medium",
      hashcatMode: 6100,
      johnFormat: "whirlpool",
    },
    {
      id: "sha3-512",
      name: "SHA3-512",
      category: "Raw hash",
      context: "SHA3-512 digest.",
      confidence: "low",
      hashcatMode: 17600,
    },
    {
      id: "keccak512",
      name: "Keccak-512",
      category: "Raw hash",
      context: "Original Keccak-512 (pre-SHA3 padding).",
      confidence: "low",
      hashcatMode: 18000,
    },
    {
      id: "streebog512",
      name: "Streebog-512 (GOST R 34.11-2012)",
      category: "Raw hash",
      context: "Russian GOST Streebog 512-bit hash.",
      confidence: "low",
      hashcatMode: 11800,
      johnFormat: "Streebog-512",
    },
    {
      id: "blake2b",
      name: "BLAKE2b-512",
      category: "Raw hash",
      context: "BLAKE2b 512-bit digest. hashcat 600 expects a $BLAKE2$ prefix.",
      confidence: "low",
    },
  ],
};
